dw_olist:
  target: prod  # your development environment
  outputs:
    prod:
      dataset: olist
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt_creds
      location: US
      method: service-account
      priority: interactive
      project: apt-theme-402300
      threads: 1
      type: bigquery
